### ISSUE TITLE
ImportError when doing pytest

### ISSUE THREAD

**Issue by breoganpardo** [astrojuanlu/ie-mbd-advanced-python#56]
Hello,
I am trying TDD process, so first I created a test function for the simple example of suming 2 numbers:
```
def test_sum_two_numbers_give_expected_result():
    a=2
    b=2
    
    expected_output=4
    assert output==expected_output
```

When I do this, the pytest works an tells me that does not work because output is not defined. So I proceed and an the 2 lines:
```
from  ie_nlp_utils import sum_numbers

def test_sum_two_numbers_give_expected_result():
    a=2
    b=2
    
    expected_output=4
    output=sum_numbers
    assert output==expected_output
```
Then in the > src/ie_nlp_utils/__init__.py

 I create the following super simple function:
```
def sum_numbers():
	return 4
```
Save the changes and when I run the pytest again I get the following error:
![image](https://user-images.githubusercontent.com/44050530/55682346-89675c00-5932-11e9-9622-b8eb1048b678.png)

¿?

**Comment by astrojuanlu** [comment]
The first error is that you have to install `ie_nlp_utils` before the tests can be run (see #55). After that, the test will fail in a different way, let me know if you figure it out :)
