### ISSUE TITLE
Problema con  dask_ml.preprocessing

### ISSUE THREAD

**Issue by paul-jm** [astrojuanlu/ie-mbd-advanced-python#63]
Hola Profe!

Estoy trabajando en el assignment individual y la verdad es que me esta costando la parte de MinMaxScaler en dask_ml.preprocessing, ya que segun el error message que me da la funcion, deberia haber la definicion de la variable 'scale_' adentro del method 'transform' como la hay en 'fit'. Segun tu experiencia, deberia de modificar directamente el archivo 'data.py' para agregar la variable 'scale_', o ves con mayor probabilidad de éxito que use sklearn.preprocessing? De manera mas amplia, deberia utilizar dask_ml en lugar de sklearn en todas las intancias? Abajo podés ver las capturas de pantallas. 

Gracias!
Paul

<img width="1440" alt="Screen Shot 2019-05-14 at 2 33 53 PM" src="https://user-images.githubusercontent.com/44065589/57698192-5319ac80-7655-11e9-80ba-58b754f29803.png">

<img width="1440" alt="Screen Shot 2019-05-14 at 1 50 15 PM" src="https://user-images.githubusercontent.com/44065589/57697953-afc89780-7654-11e9-9681-53fa103221f7.png">

**Comment by astrojuanlu** [comment]
Hola @paul-jm!

En lugar de crear un `dd.DataFrame` directamente, usa los métodos `from_array`, `from_pandas` y similares:

https://docs.dask.org/en/latest/dataframe-api.html#create-dataframes

> De manera mas amplia, deberia utilizar dask_ml en lugar de sklearn en todas las intancias?

¡Cuanto más Dask ML mejor!

**Comment by paul-jm** [comment]
Gracias!

Ahora estuve intentando correr algunas lineas de codigo en el client, recibiendo un futuro. Lo que pasa es que están tardando mucho, mientras que el notebook entero no tardaba mas 15 minutos cuando utilizábamos pandas. Es normal que pase eso? Debería de modificar algo en las capturas de pantalla?

Atte,
Paul

<img width="1440" alt="Screen Shot 2019-05-16 at 7 16 01 PM" src="https://user-images.githubusercontent.com/44065589/57873676-290bea00-780f-11e9-85f6-7080eb85c420.png">
<img width="1440" alt="Screen Shot 2019-05-16 at 7 15 58 PM" src="https://user-images.githubusercontent.com/44065589/57873677-290bea00-780f-11e9-9be7-1ee4f31270c2.png">

**Comment by astrojuanlu** [comment]
Tal vez tenga que ver con los metadatos, o con que `apply` en Dask es más lento por algún motivo - de primeras no sabría decir cuál puede ser el bottleneck sin ejecutar el código. Si te supone un problema, mándame el notebook y lo miramos con detalle.
