### ISSUE TITLE
Typo in code comment

### ISSUE THREAD

**Issue by FrancioX** [astrojuanlu/ie-mbd-advanced-python#65]
https://github.com/Juanlu001/ie-mbd-advanced-python/blob/e1a779569ebb3ddc140094706cc4270aeb8c3e6d/sessions/02_layout-unit-tests.ipynb#L322

Should read 
\# src/ie_nlp_utils/__init__.py

**Comment by astrojuanlu** [comment]
New location: https://github.com/Juanlu001/ie-mbd-advanced-python/blob/5af43b7102b0504e462c1d2cba2ecbbea1c1787b/sessions/03_layout-unit-tests.ipynb#L323
